// Code generated by mocktail; DO NOT EDIT.

package helm

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/mock"
)

// gitClientMock mock of GitClient.
type gitClientMock struct{ mock.Mock }

// newGitClientMock creates a new gitClientMock.
func newGitClientMock(tb testing.TB) *gitClientMock {
	tb.Helper()

	m := &gitClientMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}

func (_m *gitClientMock) GetDiffBetweenCommits(_ context.Context, start string, end string, diffPath string) (string, error) {
	_ret := _m.Called(start, end, diffPath)

	if _rf, ok := _ret.Get(0).(func(string, string, string) (string, error)); ok {
		return _rf(start, end, diffPath)
	}

	_ra0 := _ret.String(0)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *gitClientMock) OnGetDiffBetweenCommits(start string, end string, diffPath string) *gitClientGetDiffBetweenCommitsCall {
	return &gitClientGetDiffBetweenCommitsCall{Call: _m.Mock.On("GetDiffBetweenCommits", start, end, diffPath), Parent: _m}
}

func (_m *gitClientMock) OnGetDiffBetweenCommitsRaw(start interface{}, end interface{}, diffPath interface{}) *gitClientGetDiffBetweenCommitsCall {
	return &gitClientGetDiffBetweenCommitsCall{Call: _m.Mock.On("GetDiffBetweenCommits", start, end, diffPath), Parent: _m}
}

type gitClientGetDiffBetweenCommitsCall struct {
	*mock.Call
	Parent *gitClientMock
}

func (_c *gitClientGetDiffBetweenCommitsCall) Panic(msg string) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) Once() *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) Twice() *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) Times(i int) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) WaitUntil(w <-chan time.Time) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) After(d time.Duration) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) Run(fn func(args mock.Arguments)) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) Maybe() *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) TypedReturns(a string, b error) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) ReturnsFn(fn func(string, string, string) (string, error)) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) TypedRun(fn func(string, string, string)) *gitClientGetDiffBetweenCommitsCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_start := args.String(0)
		_end := args.String(1)
		_diffPath := args.String(2)
		fn(_start, _end, _diffPath)
	})
	return _c
}

func (_c *gitClientGetDiffBetweenCommitsCall) OnGetDiffBetweenCommits(start string, end string, diffPath string) *gitClientGetDiffBetweenCommitsCall {
	return _c.Parent.OnGetDiffBetweenCommits(start, end, diffPath)
}

func (_c *gitClientGetDiffBetweenCommitsCall) OnGetFileContent(hash string, filePath string) *gitClientGetFileContentCall {
	return _c.Parent.OnGetFileContent(hash, filePath)
}

func (_c *gitClientGetDiffBetweenCommitsCall) OnGetDiffBetweenCommitsRaw(start interface{}, end interface{}, diffPath interface{}) *gitClientGetDiffBetweenCommitsCall {
	return _c.Parent.OnGetDiffBetweenCommitsRaw(start, end, diffPath)
}

func (_c *gitClientGetDiffBetweenCommitsCall) OnGetFileContentRaw(hash interface{}, filePath interface{}) *gitClientGetFileContentCall {
	return _c.Parent.OnGetFileContentRaw(hash, filePath)
}

func (_m *gitClientMock) GetFileContent(_ context.Context, hash string, filePath string) (string, error) {
	_ret := _m.Called(hash, filePath)

	if _rf, ok := _ret.Get(0).(func(string, string) (string, error)); ok {
		return _rf(hash, filePath)
	}

	_ra0 := _ret.String(0)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *gitClientMock) OnGetFileContent(hash string, filePath string) *gitClientGetFileContentCall {
	return &gitClientGetFileContentCall{Call: _m.Mock.On("GetFileContent", hash, filePath), Parent: _m}
}

func (_m *gitClientMock) OnGetFileContentRaw(hash interface{}, filePath interface{}) *gitClientGetFileContentCall {
	return &gitClientGetFileContentCall{Call: _m.Mock.On("GetFileContent", hash, filePath), Parent: _m}
}

type gitClientGetFileContentCall struct {
	*mock.Call
	Parent *gitClientMock
}

func (_c *gitClientGetFileContentCall) Panic(msg string) *gitClientGetFileContentCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *gitClientGetFileContentCall) Once() *gitClientGetFileContentCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *gitClientGetFileContentCall) Twice() *gitClientGetFileContentCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *gitClientGetFileContentCall) Times(i int) *gitClientGetFileContentCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *gitClientGetFileContentCall) WaitUntil(w <-chan time.Time) *gitClientGetFileContentCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *gitClientGetFileContentCall) After(d time.Duration) *gitClientGetFileContentCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *gitClientGetFileContentCall) Run(fn func(args mock.Arguments)) *gitClientGetFileContentCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *gitClientGetFileContentCall) Maybe() *gitClientGetFileContentCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *gitClientGetFileContentCall) TypedReturns(a string, b error) *gitClientGetFileContentCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *gitClientGetFileContentCall) ReturnsFn(fn func(string, string) (string, error)) *gitClientGetFileContentCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *gitClientGetFileContentCall) TypedRun(fn func(string, string)) *gitClientGetFileContentCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_hash := args.String(0)
		_filePath := args.String(1)
		fn(_hash, _filePath)
	})
	return _c
}

func (_c *gitClientGetFileContentCall) OnGetDiffBetweenCommits(start string, end string, diffPath string) *gitClientGetDiffBetweenCommitsCall {
	return _c.Parent.OnGetDiffBetweenCommits(start, end, diffPath)
}

func (_c *gitClientGetFileContentCall) OnGetFileContent(hash string, filePath string) *gitClientGetFileContentCall {
	return _c.Parent.OnGetFileContent(hash, filePath)
}

func (_c *gitClientGetFileContentCall) OnGetDiffBetweenCommitsRaw(start interface{}, end interface{}, diffPath interface{}) *gitClientGetDiffBetweenCommitsCall {
	return _c.Parent.OnGetDiffBetweenCommitsRaw(start, end, diffPath)
}

func (_c *gitClientGetFileContentCall) OnGetFileContentRaw(hash interface{}, filePath interface{}) *gitClientGetFileContentCall {
	return _c.Parent.OnGetFileContentRaw(hash, filePath)
}
