name: Release with goreleaser

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.16.0'

      - name: Download dependencies
        run: go mod download

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
